# Generated by Django 5.2.3 on 2025-07-11 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='views',
            field=models.PositiveIntegerField(default=0, help_text='Количество раз, когда пост был просмотрен', verbose_name='Количество просмотров'),
        ),
    ]
