# Generated by Django 5.2.3 on 2025-07-03 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_price'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Наименование категории', 'verbose_name_plural': 'Продукты'},
        ),
    ]
