# Generated by Django 5.2.3 on 2025-07-31 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_product_options_product_is_published'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['category'], 'permissions': [('can_unpublish_product', 'может отменять публикацию продукта'), ('can_delete_product', 'может удалять продукты')], 'verbose_name': 'Продукт', 'verbose_name_plural': 'Продукты'},
        ),
    ]
